### ISSUE TITLE
no pg_hba.conf entry

### ISSUE THREAD

**Issue by whomwah** [invisiblelines/docker-fig-rails-example#1]
Have you ever got this error message?

```
FATAL:  no pg_hba.conf entry for host "<my container ip>", user "postgres", database "postgres", SSL off
 (PG::ConnectionBad)
```

Is the postgres image you are using the vanilla official one from the docker hub?

**Comment by kieranj** [comment]
No I've not had this issue before. I'm using the official postgres image from docker hub.

This image creates a pg_hba entry for the username you set to all databases on startup. 

Are you getting this error running a fresh checkout of the example code, or have you made any modifications?

**Comment by whomwah** [comment]
@kieranj thanks for the speedy response. I'm actually just hacking, and trying to understand the whole docker, fig (docker-compose), passenger-docker, rails setup and this was the first blocker I came up against. I think my issue may well be that I did not fully understand what accounts are created up front.

**Comment by kieranj** [comment]
No worries.

If you just found this repo browsing github the accompanying blog post might help - https://www.invisiblelines.com/blog/2015/01/09/using-docker-and-fig-for-a-rails-development-environment/

It doesn't cover everything in details but it should be enough to get up and running.
